apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: phongtran2606/order-service
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_URI
              value: 'mongodb://order-mongo-srv-cluster:27017/order'
            - name: NATS_URL
              value: http://nats-srv-cluster:4222
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: order-srv-cluster
spec:
  selector:
    app: order
  type: ClusterIP
  ports:
    - name: order
      protocol: TCP
      port: 3000
      targetPort: 3000
